### ISSUE TITLE
Runs with Same Name

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/kodiaq#78]
(Not sure where to keep track of this.)

Runs 402 and 403 were created so close together that they have the same name, which is causing undesirable behavior in the database (and subsequent data transfer and processing).

**Comment by sanderbreur** [comment]
Under normal conditions this would not happen, but it can always happen.
Any way to make the DAQ wait 1 min between runs?

S

Op wo 4 mei 2016 om 23:23 schreef Patrick de Perio <notifications@github.com

**Comment by tunnell** [comment]
I think it's better to have our BSON output have a better folder name.  e.g. XENON1T_TPC_run294_20160804 or whatever. This avoids this issue at least for TPC (need to think about MV and cax)

**Comment by coderdj** [comment]
This was fixed in the UI by adding a timeout for starting new runs. Report if still seen.
