### ISSUE TITLE
Keep track of time kodiaq read buffer of digitizer

### ISSUE THREAD

**Issue by sanderbreur** [XENON1T/kodiaq#79]
Kodiaq should keep track of the time it read the buffer of the digitizer. (either local comp timestamp or event_header timestamp from digitizer)

This would be usefull for the problem we now see in the clock cycles.

**Comment by coderdj** [comment]
Funny I never read this until today. This functionality was added indirectly during debugging (as log output) but I think it's safe to say the issue has been solved now.
