### ISSUE TITLE
Run stop appears asynchronous

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/kodiaq#81]
When you stop a run, the data does not stop coming at the same time for all channels:

![newplot](https://cloud.githubusercontent.com/assets/4354311/15799813/b4481a54-2a69-11e6-9df3-e1eb0c3406cc.png)

This means that near end of the run, we will get partial events, e.g.

![partial1](https://cloud.githubusercontent.com/assets/4354311/15799815/e2155280-2a69-11e6-8634-dec7227b0fd7.png)

![partial2](https://cloud.githubusercontent.com/assets/4354311/15799816/e42bb2d0-2a69-11e6-9aa7-a31a937d51a9.png)

**Comment by coderdj** [comment]
Closed in 44e0b4799cb5aa70c12251407f8d8b5d9bb740fd. Reopen if not
