### ISSUE TITLE
Large 'wake up' pulse

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/kodiaq#82]
At the start of a self-triggered run, we currently get a pulse in each channel containing some zeros, then some normal data:

![126](https://cloud.githubusercontent.com/assets/4354311/15799830/6473a79a-2a6a-11e6-8bc3-bb9ff1ba7ae4.png)

This happen even in digitizer channels without a cable plugged in. The first event in runs affected by this issue looks like this:

![event0](https://cloud.githubusercontent.com/assets/4354311/15799831/66362bf2-2a6a-11e6-8b9c-28a70a4e6cf0.png)

LED data seems unaffected:

![led_0](https://cloud.githubusercontent.com/assets/4354311/15799859/0e7bdd34-2a6b-11e6-9e65-e1f9aa123ec7.png)

**Comment by JelleAalbers** [comment]
I haven't seen this in any of the recent runs I've looked at. Perhaps this was an issue of the "old new firmware" only?

**Comment by coderdj** [comment]
Closing unless seen again. Might have been an issue of not clearing memory correctly after baseline routines or a firmware thing.
