### ISSUE TITLE
Batch of data from some digitizers out of sync near start of run

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/kodiaq#83]
Some time into the run, a batch of pulses appears out of sync. This is visible in the event distribution when running with gimp mode on:

![1432](https://cloud.githubusercontent.com/assets/4354311/16874418/80e1fae0-4a99-11e6-8555-e619ce1daa89.png)
![1433](https://cloud.githubusercontent.com/assets/4354311/16874424/82de529e-4a99-11e6-9501-ca5e7616cff5.png)

The events in the out-of-sync part appear to be partial, i.e. not all digitizers contribute:

![partial_events](https://cloud.githubusercontent.com/assets/4354311/16874477/be6f461a-4a99-11e6-9360-adc816d8d946.png)

Without gimp mode this is difficult to observe (since normal events can appear anywhere), so it is not known whether this is a problem with gimp mode only. I hope so, but I don't think we should assume it is.

**Comment by coderdj** [comment]
Fixed in 44e0b4799cb5aa70c12251407f8d8b5d9bb740fd
