### ISSUE TITLE
Trigger monitor data not available online if TPC and MV run start with same name

### ISSUE THREAD

**Issue by adambrown1** [XENON1T/kodiaq#88]
If a TPC and muon veto run start within the same minute and have the same name it is not possible to look at the trigger data on https://xenon1t-daq.lngs.infn.it/monitor/trigger_diagnostics. Examples are run 12900, 13186, 13197.

The number of trigger monitor documents shown is larger than normal, it seems the muon veto trigger data is being loaded by the website instead of the TPC trigger data.

Example list of recent runs showing two problematic ones:
<img width="235" alt="screen shot 2017-09-25 at 10 37 58" src="https://user-images.githubusercontent.com/22192046/30799593-a9c3a606-a1dd-11e7-96de-8f995a320271.png">

**Comment by coderdj** [comment]
Not kodiaq. Muon veto should not write to the same database.
